"""GLD preset for the Bollinger + RSI spike-aware strategy."""
from __future__ import annotations


# GLD behaves much more like a smoother trend instrument than UVXY/VXX.
# Keep this preset sparse: disable mean-reversion churn and reuse only the
# breakout/momentum leg with gold-sized thresholds.
PRESET: dict[str, object] = {
    "normal_long_enabled": False,
    "normal_short_enabled": False,
    "trend_bias_long_enabled": True,
    "trend_bias_fast_ema": 156,
    "trend_bias_slow_ema": 780,
    "trend_bias_lookback_bars": 90,
    "trend_bias_min_retrace_pct": 0.6,
    "trend_bias_min_momentum_120": 0.3,
    "trend_bias_min_atr_pct": 0.03,
    "trend_bias_min_rsi": 46.0,
    "trend_bias_max_rsi": 74.0,
    "trend_bias_trail_pct": 3.0,
    "trend_bias_sl_pct": 1.2,
    "trend_bias_cooldown": 120,
    "intraday_pullback_short_enabled": True,
    "intraday_pullback_rsi_trigger": 85.0,
    "intraday_pullback_rsi_fade_pts": 10.0,
    "intraday_pullback_lookback_bars": 90,
    "intraday_pullback_drop_pct": 0.8,
    "intraday_pullback_min_atr_pct": 0.04,
    "intraday_pullback_sl_pct": 0.8,
    "intraday_pullback_tp_pct": 1.2,
    "intraday_pullback_trail_pct": 0.6,
    "intraday_pullback_cooldown": 180,
    "spike_long_max": 0,
    "spike_max_entries": 0,
    "psshort_max": 0,
    "event_target_short_enabled": True,
    "event_target_min_peak_pct": 5.0,
    "event_target_confirm_drop_pct": 2.0,
    "event_target_persistent_confirm_drop_pct": 3.0,
    "event_target_completion_pct": 50.0,
    "event_target_sl_pct": 1.5,
    "decay_bounce_max": 0,
    "decay_max_entries": 0,
    "spike_gap_pct": 2.0,
    "grad_spike_lookback": 1170,
    "grad_spike_pct": 2.0,
    "grad_spike_rearm_bars": 1950,
    "psshort_window": 1950,
    "spike_lockout_bars": 390,
    "spike_profile_shock_gap_pct": 2.0,
    "spike_profile_shock_peak_pct": 4.0,
    "spike_momentum_max": 4,
    "spike_momo_atr_mult": 1.0,
    "spike_momo_momentum_pct": 0.10,
    "spike_momo_min_peak_pct": 0.75,
    "spike_momo_min_atr_pct": 0.03,
    "spike_momo_max_rsi": 90.0,
    "spike_momo_trail_pct": 2.5,
    "spike_momo_sl_pct": 1.2,
    "spike_momo_cooldown": 120,
    "dollar_strength_block_ret_30": 0.08,
    "dollar_strength_block_ret_120": 0.15,
    "rates_weakness_block_ret_30": -0.05,
    "rates_weakness_block_ret_120": -0.10,
    "gold_macro_score_enabled": True,
    "gold_macro_block_score": 1.0,
    "dollar_strength_weight": 0.7,
    "rates_weakness_weight": 1.0,
    "long_rates_weakness_weight": 0.0,
    "gold_context_assist_enabled": True,
    "gold_context_assist_min_score": 0.5,
    "gold_peer_strength_weight": 1.0,
    "gold_miners_strength_weight": 0.0,
    "gold_riskoff_strength_weight": 0.0,
}
