"""
db/database.py
──────────────
Thin SQLAlchemy wrapper for SQLite persistence.

Tables:
  trades       – every TradeRecord (open, closed, rejected, backtest)
  signals      – every Signal generated by any strategy
  portfolio    – hourly PortfolioSnapshot rows
  configs      – key/value strategy/risk config snapshots

All timestamps stored as UTC ISO-8601 strings for portability.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

from sqlalchemy import (
    Column, DateTime, Float, Integer, String, Text,
    create_engine, text,
)
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from core.logger import log


class Base(DeclarativeBase):
    pass


class TradeRow(Base):
    __tablename__ = "trades"

    id = Column(String, primary_key=True)
    symbol = Column(String, nullable=False, index=True)
    direction = Column(String)
    entry_price = Column(Float)
    take_profit = Column(Float, nullable=True)
    stop_loss = Column(Float, nullable=True)
    leverage = Column(Float)
    capital_allocated = Column(Float)
    entry_time = Column(String)
    exit_time = Column(String, nullable=True)
    exit_price = Column(Float, nullable=True)
    outcome = Column(String, nullable=True)
    leveraged_return_pct = Column(Float, nullable=True)
    pnl = Column(Float, nullable=True)
    mode = Column(String, index=True)
    strategy_id = Column(String, index=True)
    notes = Column(Text, default="")
    created_at = Column(String, default=lambda: datetime.utcnow().isoformat())

    # ── Broker-order lifecycle (NULL for local-sim rows) ────────────────
    broker_order_id     = Column(String, nullable=True, index=True)
    broker_status       = Column(String, nullable=True)
    broker_submitted_at = Column(String, nullable=True)
    filled_qty          = Column(Float,  nullable=True)
    filled_avg_price    = Column(Float,  nullable=True)
    filled_at           = Column(String, nullable=True)
    last_synced_at      = Column(String, nullable=True)


class SignalRow(Base):
    __tablename__ = "signals"

    id = Column(String, primary_key=True)
    strategy_id = Column(String, index=True)
    symbol = Column(String, index=True)
    action = Column(String)
    confidence = Column(Float)
    suggested_tp = Column(Float, nullable=True)
    suggested_sl = Column(Float, nullable=True)
    metadata_json = Column(Text, default="{}")
    generated_at = Column(String, index=True)


class PortfolioRow(Base):
    __tablename__ = "portfolio"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(String, index=True)
    total_equity = Column(Float)
    cash = Column(Float)
    open_positions_count = Column(Integer)
    daily_pnl = Column(Float)
    total_pnl = Column(Float)
    mode = Column(String)


class ConfigRow(Base):
    __tablename__ = "configs"

    key = Column(String, primary_key=True)
    value_json = Column(Text)
    updated_at = Column(String)


# ─── DB manager ─────────────────────────────────────────────────────────────

class Database:
    """Thread-safe SQLite database manager."""

    def __init__(self, db_path: Path) -> None:
        db_path.parent.mkdir(parents=True, exist_ok=True)
        self._engine = create_engine(
            f"sqlite:///{db_path}",
            connect_args={"check_same_thread": False},
        )
        Base.metadata.create_all(self._engine)
        # Light-weight forward migration: add any columns that the live model
        # declares but the on-disk table is missing. SQLite only supports
        # ADD COLUMN, which is all we need here — this is a pure append.
        self._migrate_schema()
        self._Session = sessionmaker(bind=self._engine, expire_on_commit=False)
        log.info(f"Database ready: {db_path}")

    def _migrate_schema(self) -> None:
        """
        Idempotent column additions for long-lived SQLite files created before
        a schema field was added. Safe to run on every startup.
        """
        expected_new_cols = {
            # column name → SQL type
            "broker_order_id":     "TEXT",
            "broker_status":       "TEXT",
            "broker_submitted_at": "TEXT",
            "filled_qty":          "REAL",
            "filled_avg_price":    "REAL",
            "filled_at":           "TEXT",
            "last_synced_at":      "TEXT",
        }
        with self._engine.begin() as conn:
            existing = {
                row[1] for row in conn.execute(text("PRAGMA table_info(trades)"))
            }
            for col, sql_type in expected_new_cols.items():
                if col not in existing:
                    conn.execute(text(f"ALTER TABLE trades ADD COLUMN {col} {sql_type}"))
                    log.info(f"DB migration: added trades.{col} ({sql_type})")
            # Index on broker_order_id for fast reconciliation lookups
            conn.execute(text(
                "CREATE INDEX IF NOT EXISTS ix_trades_broker_order_id "
                "ON trades(broker_order_id)"
            ))

    def session(self) -> Session:
        return self._Session()

    # ── Trades ──────────────────────────────────────────────────────────────

    def save_trade(self, trade) -> None:
        """
        Upsert a TradeRecord dataclass.

        Broker-lifecycle fields (broker_order_id, broker_status, …) are
        optional — missing attributes default to None so legacy callers
        (local-sim, backtest) keep working unchanged.
        """
        def _iso(v):
            if v is None:
                return None
            return v.isoformat() if isinstance(v, datetime) else v

        with self.session() as s:
            row = s.get(TradeRow, trade.id)
            if row is None:
                row = TradeRow(id=trade.id)
                s.add(row)
            row.symbol = trade.symbol
            row.direction = trade.direction.value if hasattr(trade.direction, "value") else trade.direction
            row.entry_price = trade.entry_price
            row.take_profit = trade.take_profit
            row.stop_loss = trade.stop_loss
            row.leverage = trade.leverage
            row.capital_allocated = trade.capital_allocated
            row.entry_time = _iso(trade.entry_time)
            row.exit_time  = _iso(trade.exit_time)
            row.exit_price = trade.exit_price
            row.outcome = trade.outcome.value if hasattr(trade.outcome, "value") else trade.outcome
            row.leveraged_return_pct = trade.leveraged_return_pct
            row.pnl = trade.pnl
            row.mode = trade.mode
            row.strategy_id = trade.strategy_id
            row.notes = trade.notes

            # ── Broker-order lifecycle (getattr → safe for legacy stand-ins) ──
            row.broker_order_id     = getattr(trade, "broker_order_id",     None)
            row.broker_status       = getattr(trade, "broker_status",       None)
            row.broker_submitted_at = _iso(getattr(trade, "broker_submitted_at", None))
            row.filled_qty          = getattr(trade, "filled_qty",          None)
            row.filled_avg_price    = getattr(trade, "filled_avg_price",    None)
            row.filled_at           = _iso(getattr(trade, "filled_at",      None))
            row.last_synced_at      = _iso(getattr(trade, "last_synced_at", None))

            s.commit()

    def get_trades(
        self,
        mode: Optional[str] = None,
        symbol: Optional[str] = None,
        limit: int = 500,
    ) -> list[dict]:
        with self.session() as s:
            q = s.query(TradeRow)
            if mode:
                q = q.filter(TradeRow.mode == mode)
            if symbol:
                q = q.filter(TradeRow.symbol == symbol)
            rows = q.order_by(TradeRow.entry_time.desc()).limit(limit).all()
            return [self._row_to_dict(r) for r in rows]

    # ── Signals ─────────────────────────────────────────────────────────────

    def save_signal(self, signal) -> None:
        with self.session() as s:
            row = SignalRow(
                id=signal.id,
                strategy_id=signal.strategy_id,
                symbol=signal.symbol,
                action=signal.action.value if hasattr(signal.action, "value") else signal.action,
                confidence=signal.confidence,
                suggested_tp=signal.suggested_tp,
                suggested_sl=signal.suggested_sl,
                metadata_json=json.dumps(signal.metadata),
                generated_at=signal.generated_at.isoformat(),
            )
            s.merge(row)
            s.commit()

    def get_signals(self, limit: int = 200) -> list[dict]:
        with self.session() as s:
            rows = s.query(SignalRow).order_by(SignalRow.generated_at.desc()).limit(limit).all()
            return [self._row_to_dict(r) for r in rows]

    # ── Portfolio snapshots ─────────────────────────────────────────────────

    def save_portfolio_snapshot(self, snap) -> None:
        with self.session() as s:
            row = PortfolioRow(
                timestamp=snap.timestamp.isoformat(),
                total_equity=snap.total_equity,
                cash=snap.cash,
                open_positions_count=snap.open_positions_count,
                daily_pnl=snap.daily_pnl,
                total_pnl=snap.total_pnl,
                mode=snap.mode,
            )
            s.add(row)
            s.commit()

    def get_portfolio_history(self, mode: Optional[str] = None, limit: int = 1000) -> list[dict]:
        with self.session() as s:
            q = s.query(PortfolioRow)
            if mode:
                q = q.filter(PortfolioRow.mode == mode)
            rows = q.order_by(PortfolioRow.timestamp.desc()).limit(limit).all()
            return [self._row_to_dict(r) for r in rows]

    # ── Config ──────────────────────────────────────────────────────────────

    def save_config(self, key: str, value: dict) -> None:
        with self.session() as s:
            row = s.get(ConfigRow, key)
            if row is None:
                row = ConfigRow(key=key)
                s.add(row)
            row.value_json = json.dumps(value)
            row.updated_at = datetime.utcnow().isoformat()
            s.commit()

    def load_config(self, key: str) -> Optional[dict]:
        with self.session() as s:
            row = s.get(ConfigRow, key)
            return json.loads(row.value_json) if row else None

    # ── Helpers ─────────────────────────────────────────────────────────────

    @staticmethod
    def _row_to_dict(row) -> dict:
        return {
            col.name: getattr(row, col.name)
            for col in row.__table__.columns
        }
